# WE CAN USE THIS FILE ALONG WITH REST CLIENT EXTENSION TO TEST ROUTES/API FETCH
# USE 3 "###" to start a new request

GET https://fakestoreapi.com/products

###

GET https://fakestoreapi.com/products/categories

###

GET http://localhost:3001/api/items

###

GET http://localhost:3000/api/users/:id
Content-Type: application/json

{
  "_id": "62cdf58dd80c6d4eb09c6296"
}

###

POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Marco",
  "email": "marco@gmail.com",
  "password": "test"
}

###

GET http://localhost:3001/api/purchases/mycart/

###

DELETE http://localhost:3000/api/users/:id
Content-Type: application/json

{
  "userId": "62cd1f2a8ea0c2843ac9adc2"
}

###

PATCH  http://localhost:3000/api/users/update/62cdf58dd80c6d4eb09c6296
Content-Type: application/json

